# file: molecule/default/converge.yml
---
- name: Converge
  hosts: all
  gather_facts: false
  roles:
    - role: nodejs_local_install
      tags:
        - node
        - nodejs
...
# vim: ft=ansible syntax=yaml.ansible
