# file: molecule/default/verify.yml
---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Retrieving latest version tag from GitHub
      ansible.builtin.shell: |
        #!/bin/bash
        set -o pipefail
        curl -s https://api.github.com/repos/nodejs/node/releases | \
        jq '.[].tag_name' | grep {{ node_version }} | sort | tail -n 1 | \
        sed 's/"//g'
      args:
        executable: /bin/bash
      changed_when: false
      register: node_tag_raw

    - name: Setting node_tag fact
      ansible.builtin.set_fact:
        node_tag: '{{ node_tag_raw.stdout }}'


    - name: Checking for node and npm
      ansible.builtin.stat:
        path: '{{ ansible_user_dir }}/.local/node-{{ node_tag }}-{{ node_arch }}'
      register: node_check

    - name: Aseerting that Node exists
      ansible.builtin.assert:
        that: node_check.stat.exists
...
# vim: ft=ansible syntax=yaml.ansible
