# file: molecule/target_user/verify.yml
---
- name: Verify
  hosts: all
  tasks:
    - name: Including vars
      ansible.builtin.include_vars:
        file: ../../vars/main.yml

    - name: Gathering facts
      ansible.builtin.setup:
        gather_subset: min

    - name: Retrieving latest version tag from GitHub
      ansible.builtin.shell: |
        #!/bin/bash
        set -o pipefail
        curl -s https://api.github.com/repos/nodejs/node/releases | \
        jq '.[].tag_name' | grep {{ node_version }} | sort | tail -n 1 | \
        sed 's/"//g'
      args:
        executable: /bin/bash
      changed_when: false
      register: node_tag_raw

    - name: Setting node_tag fact
      ansible.builtin.set_fact:
        node_tag: '{{ node_tag_raw.stdout }}'

    - name: Setting NodeJS Arcthitecture fact
      ansible.builtin.set_fact:
        node_arch: '{{ node_arch_options[ansible_architecture] | default("linux-x64") }}'

    - name: Checking for node and npm
      ansible.builtin.stat:
        path: '{{ ansible_user_dir }}/.local/node-{{ node_tag }}-{{ node_arch }}'
      register: node_check

    - name: Aseerting that Node exists
      ansible.builtin.assert:
        that: node_check.stat.exists
...
# vim: ft=ansible syntax=yaml.ansible
